graph TD
    Start([Начало]) --> Input[/Ввод x, a, b/]
    Input --> ODZ1{x >= 7?}
    ODZ1 -- Да --> Error1[/Ошибка: Не определено/]
    Error1 --> End([Конец])
    ODZ1 -- Нет --> Map[Код диапазона x]
    Map --> Switch{Switch Код}
    Switch -- 1: x < 4 --> Calc1[f = cos x]
    Switch -- 2: x = 4 --> Calc2[f = x^3 - bx + 1]
    Switch -- 3: 4 < x < 7 --> ODZ2{ax < 0?}
    ODZ2 -- Да --> Error2[/Ошибка: Отриц. корень/]
    Error2 --> End
    ODZ2 -- Нет --> Calc3[f = sqrt ax]
    Calc1 --> Success[/Вывод f_x/]
    Calc2 --> Success
    Calc3 --> Success
    Success --> End
